import { db, brandsTable, deviceModelsTable, repairServicesTable } from "@workspace/db";
import { sql } from "drizzle-orm";

function slug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

const REPAIR_SERVICES = [
  {
    name: "Display Replacement",
    slug: "display-replacement",
    description: "Complete display unit replacement with original quality screen.",
    imageUrl: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 4999, priceHigh: 2999, priceMid: 1499, priceBudget: 999,
    repairTime: "45-60 min", warranty: "6 Months", isPopular: true, sortOrder: 1,
  },
  {
    name: "Battery Replacement",
    slug: "battery-replacement",
    description: "Replace degraded battery with a high-capacity OEM-grade unit.",
    imageUrl: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 2999, priceHigh: 1999, priceMid: 1299, priceBudget: 699,
    repairTime: "30-45 min", warranty: "12 Months", isPopular: true, sortOrder: 2,
  },
  {
    name: "Back Glass Replacement",
    slug: "back-glass-replacement",
    description: "Replace cracked or shattered rear glass panel.",
    imageUrl: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 3999, priceHigh: 1799, priceMid: 1199, priceBudget: 799,
    repairTime: "60-90 min", warranty: "3 Months", isPopular: true, sortOrder: 3,
  },
  {
    name: "Charging Port Repair",
    slug: "charging-port-repair",
    description: "Fix or replace faulty USB/Lightning charging port.",
    imageUrl: "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 1499, priceHigh: 999, priceMid: 699, priceBudget: 499,
    repairTime: "30-45 min", warranty: "3 Months", isPopular: true, sortOrder: 4,
  },
  {
    name: "Mic Repair",
    slug: "mic-repair",
    description: "Restore microphone clarity for calls and voice recording.",
    imageUrl: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 1499, priceHigh: 999, priceMid: 699, priceBudget: 499,
    repairTime: "30-45 min", warranty: "3 Months", isPopular: false, sortOrder: 5,
  },
  {
    name: "Receiver Repair",
    slug: "receiver-repair",
    description: "Fix earpiece speaker for clear in-call audio.",
    imageUrl: "https://images.unsplash.com/photo-1512054502232-10a0a035d672?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 1499, priceHigh: 999, priceMid: 699, priceBudget: 499,
    repairTime: "30-45 min", warranty: "3 Months", isPopular: false, sortOrder: 6,
  },
  {
    name: "Speaker Repair",
    slug: "speaker-repair",
    description: "Replace or repair loud speaker for clear audio playback.",
    imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 1999, priceHigh: 1299, priceMid: 899, priceBudget: 599,
    repairTime: "30-45 min", warranty: "3 Months", isPopular: false, sortOrder: 7,
  },
  {
    name: "Camera Repair",
    slug: "camera-repair",
    description: "Replace rear camera module for clear, sharp photos.",
    imageUrl: "https://images.unsplash.com/photo-1606986628253-f1d2f9e4a54c?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 3999, priceHigh: 2499, priceMid: 1499, priceBudget: 899,
    repairTime: "45-60 min", warranty: "3 Months", isPopular: true, sortOrder: 8,
  },
  {
    name: "Front Camera Repair",
    slug: "front-camera-repair",
    description: "Replace front selfie camera for clear video calls and selfies.",
    imageUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 2499, priceHigh: 1499, priceMid: 999, priceBudget: 699,
    repairTime: "30-45 min", warranty: "3 Months", isPopular: false, sortOrder: 9,
  },
  {
    name: "Power Button Repair",
    slug: "power-button-repair",
    description: "Fix unresponsive or stuck power/lock button.",
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 1299, priceHigh: 899, priceMid: 699, priceBudget: 499,
    repairTime: "20-30 min", warranty: "3 Months", isPopular: false, sortOrder: 10,
  },
  {
    name: "Volume Button Repair",
    slug: "volume-button-repair",
    description: "Repair or replace unresponsive volume up/down buttons.",
    imageUrl: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 1299, priceHigh: 899, priceMid: 699, priceBudget: 499,
    repairTime: "20-30 min", warranty: "3 Months", isPopular: false, sortOrder: 11,
  },
  {
    name: "Fingerprint Repair",
    slug: "fingerprint-repair",
    description: "Restore fingerprint sensor for secure biometric unlock.",
    imageUrl: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 1999, priceHigh: 1299, priceMid: 899, priceBudget: 699,
    repairTime: "30-45 min", warranty: "3 Months", isPopular: false, sortOrder: 12,
  },
  {
    name: "Face ID Repair",
    slug: "face-id-repair",
    description: "Restore Face ID / Face Recognition for secure facial unlock.",
    imageUrl: "https://images.unsplash.com/photo-1555954679-7d1dd64e9a65?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 4999, priceHigh: 2999, priceMid: 1499, priceBudget: 999,
    repairTime: "45-60 min", warranty: "6 Months", isPopular: false, sortOrder: 13,
  },
  {
    name: "Motherboard Repair",
    slug: "motherboard-repair",
    description: "Advanced PCB-level repair for no-power or logic board issues.",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 6999, priceHigh: 4999, priceMid: 2999, priceBudget: 1999,
    repairTime: "2-4 hours", warranty: "6 Months", isPopular: false, sortOrder: 14,
  },
  {
    name: "Network Repair",
    slug: "network-repair",
    description: "Fix SIM card, Wi-Fi, or network antenna connectivity issues.",
    imageUrl: "https://images.unsplash.com/photo-1562159278-1253a58da141?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 1999, priceHigh: 1499, priceMid: 999, priceBudget: 699,
    repairTime: "30-60 min", warranty: "3 Months", isPopular: false, sortOrder: 15,
  },
  {
    name: "Software Repair",
    slug: "software-repair",
    description: "Fix software issues, bootloop, or stuck on logo problems.",
    imageUrl: "https://images.unsplash.com/photo-1555421689-491e316e91f9?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 999, priceHigh: 799, priceMid: 599, priceBudget: 499,
    repairTime: "30-60 min", warranty: "1 Month", isPopular: false, sortOrder: 16,
  },
  {
    name: "Water Damage Repair",
    slug: "water-damage-repair",
    description: "Complete diagnosis and treatment for liquid-damaged devices.",
    imageUrl: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 2999, priceHigh: 1999, priceMid: 1499, priceBudget: 999,
    repairTime: "1-2 hours", warranty: "3 Months", isPopular: false, sortOrder: 17,
  },
  {
    name: "Flashlight Repair",
    slug: "flashlight-repair",
    description: "Repair rear torch/flash not working or flickering.",
    imageUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 999, priceHigh: 799, priceMid: 599, priceBudget: 499,
    repairTime: "20-30 min", warranty: "3 Months", isPopular: false, sortOrder: 18,
  },
  {
    name: "Housing Replacement",
    slug: "housing-replacement",
    description: "Replace scratched or bent outer frame and housing.",
    imageUrl: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 3999, priceHigh: 2499, priceMid: 1499, priceBudget: 999,
    repairTime: "60-90 min", warranty: "3 Months", isPopular: false, sortOrder: 19,
  },
  {
    name: "Vibration Motor Repair",
    slug: "vibration-motor-repair",
    description: "Replace faulty haptic / vibration motor for tactile feedback.",
    imageUrl: "https://images.unsplash.com/photo-1484417894907-623942c8ee29?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 1299, priceHigh: 899, priceMid: 699, priceBudget: 499,
    repairTime: "20-30 min", warranty: "3 Months", isPopular: false, sortOrder: 20,
  },
  {
    name: "SIM Tray Replacement",
    slug: "sim-tray-replacement",
    description: "Replace broken or stuck SIM card tray.",
    imageUrl: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=600&h=400&fit=crop&q=80&fm=webp",
    pricePremium: 499, priceHigh: 399, priceMid: 299, priceBudget: 199,
    repairTime: "10-20 min", warranty: "1 Month", isPopular: false, sortOrder: 21,
  },
];

const BRANDS_DATA = [
  {
    name: "Apple", slug: "apple", logoSlug: "apple", tier: "premium", isPopular: true, sortOrder: 1,
    models: [
      { name: "iPhone 6", popular: false, order: 35 },
      { name: "iPhone 6 Plus", popular: false, order: 34 },
      { name: "iPhone 6s", popular: false, order: 33 },
      { name: "iPhone 6s Plus", popular: false, order: 32 },
      { name: "iPhone 7", popular: false, order: 31 },
      { name: "iPhone 7 Plus", popular: false, order: 30 },
      { name: "iPhone 8", popular: false, order: 29 },
      { name: "iPhone 8 Plus", popular: false, order: 28 },
      { name: "iPhone X", popular: false, order: 27 },
      { name: "iPhone XR", popular: false, order: 26 },
      { name: "iPhone XS", popular: false, order: 25 },
      { name: "iPhone XS Max", popular: false, order: 24 },
      { name: "iPhone 11", popular: false, order: 23 },
      { name: "iPhone 11 Pro", popular: false, order: 22 },
      { name: "iPhone 11 Pro Max", popular: false, order: 21 },
      { name: "iPhone 12", popular: false, order: 20 },
      { name: "iPhone 12 Mini", popular: false, order: 19 },
      { name: "iPhone 12 Pro", popular: false, order: 18 },
      { name: "iPhone 12 Pro Max", popular: false, order: 17 },
      { name: "iPhone 13", popular: true, order: 16 },
      { name: "iPhone 13 Mini", popular: false, order: 15 },
      { name: "iPhone 13 Pro", popular: true, order: 14 },
      { name: "iPhone 13 Pro Max", popular: true, order: 13 },
      { name: "iPhone 14", popular: true, order: 12 },
      { name: "iPhone 14 Plus", popular: false, order: 11 },
      { name: "iPhone 14 Pro", popular: true, order: 10 },
      { name: "iPhone 14 Pro Max", popular: true, order: 9 },
      { name: "iPhone 15", popular: true, order: 8 },
      { name: "iPhone 15 Plus", popular: false, order: 7 },
      { name: "iPhone 15 Pro", popular: true, order: 6 },
      { name: "iPhone 15 Pro Max", popular: true, order: 5 },
      { name: "iPhone 16", popular: true, order: 4 },
      { name: "iPhone 16 Plus", popular: false, order: 3 },
      { name: "iPhone 16 Pro", popular: true, order: 2 },
      { name: "iPhone 16 Pro Max", popular: true, order: 1 },
    ],
  },
  {
    name: "Samsung", slug: "samsung", logoSlug: "samsung", tier: "high", isPopular: true, sortOrder: 2,
    models: [
      { name: "Galaxy S25 Ultra", popular: true, order: 1 },
      { name: "Galaxy S25+", popular: true, order: 2 },
      { name: "Galaxy S25", popular: true, order: 3 },
      { name: "Galaxy S24 Ultra", popular: true, order: 4 },
      { name: "Galaxy S24+", popular: false, order: 5 },
      { name: "Galaxy S24", popular: true, order: 6 },
      { name: "Galaxy S23 Ultra", popular: false, order: 7 },
      { name: "Galaxy S23+", popular: false, order: 8 },
      { name: "Galaxy S23", popular: false, order: 9 },
      { name: "Galaxy S23 FE", popular: false, order: 10 },
      { name: "Galaxy S22 Ultra", popular: false, order: 11 },
      { name: "Galaxy Note 20 Ultra", popular: false, order: 12 },
      { name: "Galaxy Note 20", popular: false, order: 13 },
      { name: "Galaxy A55 5G", popular: true, order: 14 },
      { name: "Galaxy A35 5G", popular: true, order: 15 },
      { name: "Galaxy A25 5G", popular: false, order: 16 },
      { name: "Galaxy A15 5G", popular: false, order: 17 },
      { name: "Galaxy A05", popular: false, order: 18 },
      { name: "Galaxy M55 5G", popular: false, order: 19 },
      { name: "Galaxy M35 5G", popular: false, order: 20 },
      { name: "Galaxy M15 5G", popular: false, order: 21 },
      { name: "Galaxy Z Fold 6", popular: false, order: 22 },
      { name: "Galaxy Z Fold 5", popular: false, order: 23 },
      { name: "Galaxy Z Flip 6", popular: false, order: 24 },
      { name: "Galaxy Z Flip 5", popular: false, order: 25 },
      { name: "Galaxy F55 5G", popular: false, order: 26 },
      { name: "Galaxy F35 5G", popular: false, order: 27 },
      { name: "Galaxy F15 5G", popular: false, order: 28 },
    ],
  },
  {
    name: "OnePlus", slug: "oneplus", logoSlug: "oneplus", tier: "mid", isPopular: true, sortOrder: 3,
    models: [
      { name: "OnePlus 13", popular: true, order: 1 },
      { name: "OnePlus 13R", popular: true, order: 2 },
      { name: "OnePlus 12", popular: true, order: 3 },
      { name: "OnePlus 12R", popular: false, order: 4 },
      { name: "OnePlus 11", popular: true, order: 5 },
      { name: "OnePlus 11R", popular: false, order: 6 },
      { name: "OnePlus 10T", popular: false, order: 7 },
      { name: "OnePlus 10 Pro", popular: false, order: 8 },
      { name: "OnePlus 9 Pro", popular: false, order: 9 },
      { name: "OnePlus 9", popular: false, order: 10 },
      { name: "OnePlus 9R", popular: false, order: 11 },
      { name: "OnePlus Nord 4", popular: true, order: 12 },
      { name: "OnePlus Nord CE 4", popular: true, order: 13 },
      { name: "OnePlus Nord CE 4 Lite", popular: false, order: 14 },
      { name: "OnePlus Nord 3", popular: false, order: 15 },
      { name: "OnePlus Nord 2T", popular: false, order: 16 },
      { name: "OnePlus Open", popular: false, order: 17 },
    ],
  },
  {
    name: "Xiaomi", slug: "xiaomi", logoSlug: "xiaomi", tier: "mid", isPopular: true, sortOrder: 4,
    models: [
      { name: "Xiaomi 14 Ultra", popular: true, order: 1 },
      { name: "Xiaomi 14", popular: true, order: 2 },
      { name: "Xiaomi 13T Pro", popular: false, order: 3 },
      { name: "Xiaomi 13T", popular: false, order: 4 },
      { name: "Xiaomi 13 Pro", popular: false, order: 5 },
      { name: "Xiaomi 13", popular: false, order: 6 },
      { name: "Xiaomi 12T Pro", popular: false, order: 7 },
      { name: "Xiaomi 12T", popular: false, order: 8 },
      { name: "Xiaomi 12 Pro", popular: false, order: 9 },
      { name: "Xiaomi 12", popular: false, order: 10 },
      { name: "Xiaomi 11T Pro", popular: false, order: 11 },
      { name: "Xiaomi 11T", popular: false, order: 12 },
      { name: "Xiaomi Civi 4 Pro", popular: false, order: 13 },
      { name: "Xiaomi Civi 3", popular: false, order: 14 },
      { name: "Xiaomi Mix Fold 4", popular: false, order: 15 },
    ],
  },
  {
    name: "Redmi", slug: "redmi", logoSlug: "xiaomi", tier: "budget", isPopular: true, sortOrder: 5,
    models: [
      { name: "Redmi Note 14 Pro+", popular: true, order: 1 },
      { name: "Redmi Note 14 Pro", popular: true, order: 2 },
      { name: "Redmi Note 14", popular: true, order: 3 },
      { name: "Redmi Note 13 Pro+", popular: true, order: 4 },
      { name: "Redmi Note 13 Pro", popular: true, order: 5 },
      { name: "Redmi Note 13", popular: false, order: 6 },
      { name: "Redmi Note 12 Pro+", popular: false, order: 7 },
      { name: "Redmi Note 12 Pro", popular: false, order: 8 },
      { name: "Redmi Note 12", popular: false, order: 9 },
      { name: "Redmi Note 11 Pro+", popular: false, order: 10 },
      { name: "Redmi Note 11 Pro", popular: false, order: 11 },
      { name: "Redmi Note 11", popular: false, order: 12 },
      { name: "Redmi 14C", popular: false, order: 13 },
      { name: "Redmi 13C", popular: false, order: 14 },
      { name: "Redmi 13", popular: false, order: 15 },
      { name: "Redmi A3", popular: false, order: 16 },
    ],
  },
  {
    name: "Poco", slug: "poco", logoSlug: "xiaomi", tier: "mid", isPopular: false, sortOrder: 6,
    models: [
      { name: "POCO X7 Pro", popular: true, order: 1 },
      { name: "POCO X7", popular: true, order: 2 },
      { name: "POCO X6 Pro", popular: true, order: 3 },
      { name: "POCO X6", popular: false, order: 4 },
      { name: "POCO X5 Pro 5G", popular: false, order: 5 },
      { name: "POCO X5 5G", popular: false, order: 6 },
      { name: "POCO F6 Pro", popular: false, order: 7 },
      { name: "POCO F6", popular: false, order: 8 },
      { name: "POCO F5", popular: false, order: 9 },
      { name: "POCO M7 Pro 5G", popular: false, order: 10 },
      { name: "POCO M6 Pro", popular: false, order: 11 },
      { name: "POCO C75 5G", popular: false, order: 12 },
      { name: "POCO C65", popular: false, order: 13 },
    ],
  },
  {
    name: "Realme", slug: "realme", logoSlug: "realme", tier: "budget", isPopular: false, sortOrder: 7,
    models: [
      { name: "Realme GT 7 Pro", popular: true, order: 1 },
      { name: "Realme GT 7", popular: true, order: 2 },
      { name: "Realme GT 6", popular: false, order: 3 },
      { name: "Realme GT 6T", popular: false, order: 4 },
      { name: "Realme GT Neo 6", popular: false, order: 5 },
      { name: "Realme 14 Pro+", popular: true, order: 6 },
      { name: "Realme 14 Pro", popular: false, order: 7 },
      { name: "Realme 14", popular: false, order: 8 },
      { name: "Realme 13 Pro+", popular: false, order: 9 },
      { name: "Realme 13 Pro", popular: false, order: 10 },
      { name: "Realme Narzo 70 Pro", popular: false, order: 11 },
      { name: "Realme Narzo 70", popular: false, order: 12 },
      { name: "Realme C67", popular: false, order: 13 },
      { name: "Realme C55", popular: false, order: 14 },
      { name: "Realme C51", popular: false, order: 15 },
    ],
  },
  {
    name: "Vivo", slug: "vivo", logoSlug: "vivo", tier: "mid", isPopular: false, sortOrder: 8,
    models: [
      { name: "vivo X200 Pro", popular: true, order: 1 },
      { name: "vivo X200", popular: true, order: 2 },
      { name: "vivo X100 Pro", popular: false, order: 3 },
      { name: "vivo X100", popular: false, order: 4 },
      { name: "vivo V40 Pro", popular: true, order: 5 },
      { name: "vivo V40", popular: false, order: 6 },
      { name: "vivo V30 Pro", popular: false, order: 7 },
      { name: "vivo V30", popular: false, order: 8 },
      { name: "vivo V29 Pro", popular: false, order: 9 },
      { name: "vivo V29", popular: false, order: 10 },
      { name: "vivo T3 Ultra", popular: false, order: 11 },
      { name: "vivo T3 Pro", popular: false, order: 12 },
      { name: "vivo T3 5G", popular: false, order: 13 },
      { name: "vivo Y200 Pro", popular: false, order: 14 },
      { name: "vivo Y100", popular: false, order: 15 },
    ],
  },
  {
    name: "Oppo", slug: "oppo", logoSlug: "oppo", tier: "mid", isPopular: false, sortOrder: 9,
    models: [
      { name: "OPPO Find X8 Pro", popular: true, order: 1 },
      { name: "OPPO Find X8", popular: true, order: 2 },
      { name: "OPPO Find X7 Ultra", popular: false, order: 3 },
      { name: "OPPO Find X7", popular: false, order: 4 },
      { name: "OPPO Reno 13 Pro", popular: true, order: 5 },
      { name: "OPPO Reno 13", popular: false, order: 6 },
      { name: "OPPO Reno 12 Pro", popular: false, order: 7 },
      { name: "OPPO Reno 12", popular: false, order: 8 },
      { name: "OPPO Reno 11 Pro", popular: false, order: 9 },
      { name: "OPPO Reno 11", popular: false, order: 10 },
      { name: "OPPO Reno 10 Pro+", popular: false, order: 11 },
      { name: "OPPO A3 Pro", popular: false, order: 12 },
      { name: "OPPO A79 5G", popular: false, order: 13 },
      { name: "OPPO A78 5G", popular: false, order: 14 },
      { name: "OPPO A60", popular: false, order: 15 },
    ],
  },
  {
    name: "iQOO", slug: "iqoo", logoSlug: "iqoo", tier: "mid", isPopular: false, sortOrder: 10,
    models: [
      { name: "iQOO 13", popular: true, order: 1 },
      { name: "iQOO 12", popular: true, order: 2 },
      { name: "iQOO 11S", popular: false, order: 3 },
      { name: "iQOO 11", popular: false, order: 4 },
      { name: "iQOO Z9 Turbo+", popular: true, order: 5 },
      { name: "iQOO Z9 Turbo", popular: false, order: 6 },
      { name: "iQOO Z9 5G", popular: false, order: 7 },
      { name: "iQOO Z8 Pro", popular: false, order: 8 },
      { name: "iQOO Z8 5G", popular: false, order: 9 },
      { name: "iQOO Z7 Pro", popular: false, order: 10 },
      { name: "iQOO Z7 5G", popular: false, order: 11 },
      { name: "iQOO Neo 9 Pro", popular: false, order: 12 },
      { name: "iQOO Neo 9", popular: false, order: 13 },
    ],
  },
  {
    name: "Nothing", slug: "nothing", logoSlug: "nothing", tier: "mid", isPopular: false, sortOrder: 11,
    models: [
      { name: "Nothing Phone 3", popular: true, order: 1 },
      { name: "Nothing Phone 2a Plus", popular: true, order: 2 },
      { name: "Nothing Phone 2a", popular: true, order: 3 },
      { name: "Nothing Phone 2", popular: false, order: 4 },
      { name: "Nothing Phone 1", popular: false, order: 5 },
      { name: "CMF Phone 2 Pro", popular: false, order: 6 },
      { name: "CMF Phone 1", popular: false, order: 7 },
    ],
  },
  {
    name: "Google Pixel", slug: "google", logoSlug: "google", tier: "high", isPopular: false, sortOrder: 12,
    models: [
      { name: "Pixel 9 Pro XL", popular: true, order: 1 },
      { name: "Pixel 9 Pro Fold", popular: false, order: 2 },
      { name: "Pixel 9 Pro", popular: true, order: 3 },
      { name: "Pixel 9", popular: true, order: 4 },
      { name: "Pixel 8 Pro", popular: true, order: 5 },
      { name: "Pixel 8a", popular: false, order: 6 },
      { name: "Pixel 8", popular: false, order: 7 },
      { name: "Pixel 7 Pro", popular: false, order: 8 },
      { name: "Pixel 7a", popular: false, order: 9 },
      { name: "Pixel 7", popular: false, order: 10 },
      { name: "Pixel 6 Pro", popular: false, order: 11 },
      { name: "Pixel 6a", popular: false, order: 12 },
      { name: "Pixel 6", popular: false, order: 13 },
    ],
  },
  {
    name: "Motorola", slug: "motorola", logoSlug: "motorola", tier: "mid", isPopular: false, sortOrder: 13,
    models: [
      { name: "Motorola Edge 50 Ultra", popular: true, order: 1 },
      { name: "Motorola Edge 50 Pro", popular: true, order: 2 },
      { name: "Motorola Edge 50 Fusion", popular: false, order: 3 },
      { name: "Motorola Edge 50", popular: false, order: 4 },
      { name: "Motorola Edge 40 Pro", popular: false, order: 5 },
      { name: "Motorola Edge 40 Neo", popular: false, order: 6 },
      { name: "Motorola Edge 40", popular: false, order: 7 },
      { name: "Moto G85 5G", popular: true, order: 8 },
      { name: "Moto G84 5G", popular: false, order: 9 },
      { name: "Moto G64 5G", popular: false, order: 10 },
      { name: "Moto G54 5G", popular: false, order: 11 },
      { name: "Moto G44 5G", popular: false, order: 12 },
      { name: "Moto G34 5G", popular: false, order: 13 },
      { name: "Moto G14", popular: false, order: 14 },
      { name: "Motorola Razr 50 Ultra", popular: false, order: 15 },
    ],
  },
  {
    name: "Nokia", slug: "nokia", logoSlug: "nokia", tier: "budget", isPopular: false, sortOrder: 14,
    models: [
      { name: "Nokia G42 5G", popular: true, order: 1 },
      { name: "Nokia G21", popular: false, order: 2 },
      { name: "Nokia G20", popular: false, order: 3 },
      { name: "Nokia G11 Plus", popular: false, order: 4 },
      { name: "Nokia G11", popular: false, order: 5 },
      { name: "Nokia C32", popular: false, order: 6 },
      { name: "Nokia C22", popular: false, order: 7 },
      { name: "Nokia C21", popular: false, order: 8 },
      { name: "Nokia C12", popular: false, order: 9 },
      { name: "Nokia XR21", popular: false, order: 10 },
      { name: "Nokia XR20", popular: false, order: 11 },
    ],
  },
  {
    name: "Honor", slug: "honor", logoSlug: "honor", tier: "mid", isPopular: false, sortOrder: 15,
    models: [
      { name: "Honor Magic7 Pro", popular: true, order: 1 },
      { name: "Honor Magic6 Pro", popular: false, order: 2 },
      { name: "Honor Magic6", popular: false, order: 3 },
      { name: "Honor Magic V3", popular: false, order: 4 },
      { name: "Honor Magic5 Pro", popular: false, order: 5 },
      { name: "Honor 200 Pro", popular: true, order: 6 },
      { name: "Honor 200", popular: false, order: 7 },
      { name: "Honor 90 Smart", popular: false, order: 8 },
      { name: "Honor X9b", popular: false, order: 9 },
      { name: "Honor X8b", popular: false, order: 10 },
      { name: "Honor X7b", popular: false, order: 11 },
    ],
  },
  {
    name: "Asus", slug: "asus", logoSlug: "asus", tier: "mid", isPopular: false, sortOrder: 16,
    models: [
      { name: "ROG Phone 9 Pro", popular: true, order: 1 },
      { name: "ROG Phone 9", popular: true, order: 2 },
      { name: "ROG Phone 8 Pro", popular: false, order: 3 },
      { name: "ROG Phone 8", popular: false, order: 4 },
      { name: "ROG Phone 7 Ultimate", popular: false, order: 5 },
      { name: "ROG Phone 7", popular: false, order: 6 },
      { name: "Zenfone 11 Ultra", popular: true, order: 7 },
      { name: "Zenfone 10", popular: false, order: 8 },
      { name: "Zenfone 9", popular: false, order: 9 },
      { name: "Zenfone 8", popular: false, order: 10 },
    ],
  },
  {
    name: "Infinix", slug: "infinix", logoSlug: "infinix", tier: "budget", isPopular: false, sortOrder: 17,
    models: [
      { name: "Infinix Zero 40 5G", popular: true, order: 1 },
      { name: "Infinix Zero 30 5G", popular: false, order: 2 },
      { name: "Infinix Note 40 Pro+", popular: true, order: 3 },
      { name: "Infinix Note 40 Pro", popular: false, order: 4 },
      { name: "Infinix Note 40", popular: false, order: 5 },
      { name: "Infinix Hot 50 Pro+", popular: false, order: 6 },
      { name: "Infinix Hot 40 Pro", popular: false, order: 7 },
      { name: "Infinix Hot 40", popular: false, order: 8 },
      { name: "Infinix GT 20 Pro", popular: false, order: 9 },
      { name: "Infinix Smart 9", popular: false, order: 10 },
      { name: "Infinix Smart 8", popular: false, order: 11 },
    ],
  },
  {
    name: "Tecno", slug: "tecno", logoSlug: "tecno", tier: "budget", isPopular: false, sortOrder: 18,
    models: [
      { name: "Tecno Phantom X2 Pro", popular: true, order: 1 },
      { name: "Tecno Phantom V Fold 2", popular: false, order: 2 },
      { name: "Tecno Camon 30 Pro 5G", popular: true, order: 3 },
      { name: "Tecno Camon 30", popular: false, order: 4 },
      { name: "Tecno Camon 20 Pro", popular: false, order: 5 },
      { name: "Tecno Camon 20", popular: false, order: 6 },
      { name: "Tecno Pova 6 Pro", popular: false, order: 7 },
      { name: "Tecno Pova 6", popular: false, order: 8 },
      { name: "Tecno Pova 5 Pro", popular: false, order: 9 },
      { name: "Tecno Spark 20 Pro+", popular: false, order: 10 },
      { name: "Tecno Spark 20", popular: false, order: 11 },
    ],
  },
];

async function main() {
  console.log("🌱 Seeding catalog...");

  // Clear existing catalog data
  await db.execute(sql`TRUNCATE TABLE device_models CASCADE`);
  await db.execute(sql`TRUNCATE TABLE brands CASCADE`);
  await db.execute(sql`TRUNCATE TABLE repair_services CASCADE`);

  // Seed repair services
  console.log("  → Inserting 21 repair services...");
  await db.insert(repairServicesTable).values(REPAIR_SERVICES);

  // Seed brands + models
  console.log("  → Inserting 18 brands with models...");
  for (const brand of BRANDS_DATA) {
    const [inserted] = await db
      .insert(brandsTable)
      .values({
        name: brand.name,
        slug: brand.slug,
        logoSlug: brand.logoSlug,
        tier: brand.tier,
        isPopular: brand.isPopular,
        sortOrder: brand.sortOrder,
      })
      .returning();

    const models = brand.models.map((m) => ({
      brandId: inserted.id,
      name: m.name,
      slug: slug(m.name),
      isPopular: m.popular,
      sortOrder: m.order,
    }));

    await db.insert(deviceModelsTable).values(models);
    console.log(`    ✓ ${brand.name}: ${models.length} models`);
  }

  const totalModels = BRANDS_DATA.reduce((sum, b) => sum + b.models.length, 0);
  console.log(`\n✅ Done! Seeded 18 brands, ${totalModels} models, 21 repair services.`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
